// scoring.js — exact port of market_int_core::model scoring
// (calculate_put_chain_score_components + calculate_put_score_parts +
// calculate_max_drop_safety + top_picks_from_rows), operating on the frozen
// §4 result-document Row schema (crates/webapp/src/result.rs).
//
// Parity is pinned by scripts/run-parity.mjs (part of `npm run smoke`)
// against Rust-executed test vectors from crates/core/src/model.rs tests and
// against the formula-true sample fixture regenerated by the Rust suite. If
// the Rust scorer changes, run-parity.mjs (and then this file) must change
// with it.
//
// Hard limits by construction: rows dropped pipeline-side by the presentation
// fence (|delta| > PRESENT_MAX_ABS_DELTA) and the earnings-window upper-half
// rule are absent from the document; no client-side re-weighting can surface
// them. Those drops are therefore intentionally NOT re-applied here — every
// row this module sees already passed them.

export const PRODUCTION = Object.freeze({
  weightSharpe: 0.20,
  weightSafety: 0.40,
  weightReturn: 0.40,
  weightTrend: 0.0,
  minRateOfReturn: 0.20,
  idealReturn: 0.80,
  trendScoreFloor: 1.02,
  trendScoreBand: 0.06,
  earningsSafetyMultiplier: 0.5,
  topPicksCount: 3,
});

const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x));

// Mirrors calculate_max_drop_safety: strike position in the band
// [strike_from, strike_to] — 1.0 at the deep end, 0.0 at the shallow end,
// 0.5 for a degenerate (zero-width) band, clamped outside.
export function maxDropSafety(strike, from, to) {
  const band = to - from;
  if (Math.abs(band) < 1e-9) return 0.5;
  return clamp((to - strike) / band, 0.0, 1.0);
}

// Mirrors calculate_put_score_parts (pre-filters + weighted 20/40/40 parts).
// Returns null when a pre-filter fails; `total` is exactly the sum of parts.
export function scoreParts(sharpe, safety, rateOfReturn, trendShort, p = PRODUCTION) {
  if (rateOfReturn < p.minRateOfReturn) return null;
  if (sharpe <= 0) return null;
  const sharpeNorm = clamp(sharpe / 2.0, 0.0, 1.0);
  const safetyNorm = clamp(safety, 0.0, 1.0);
  const returnNorm = Math.min(rateOfReturn / p.idealReturn, 1.0);
  const trendNorm = clamp(
    (trendShort - p.trendScoreFloor) / p.trendScoreBand,
    0.0,
    1.0,
  );
  const parts = {
    sharpe: p.weightSharpe * sharpeNorm,
    safety: p.weightSafety * safetyNorm,
    return: p.weightReturn * returnNorm,
    trend: p.weightTrend * trendNorm,
  };
  parts.total =
    parts.sharpe + parts.safety + parts.return + parts.trend;
  return parts;
}

// Mirrors calculate_put_chain_score_components over one persisted Row.
// Field conventions that matter:
//   - sharpe_ratio / trend_short null ⇔ the Rust scoring default of 0.0
//   - earnings_before_expiry non-null ⇔ earnings_in_window → safety ×0.5
//   - delta null → max_drop band fallback for safety
//   - rate_of_return null (non-finite sanitized at serialization) → unscored
export function rescoreRow(row, p = PRODUCTION) {
  const ror = row.rate_of_return;
  if (ror == null || !Number.isFinite(ror)) return null;
  const sharpe = row.sharpe_ratio ?? 0.0;
  const trendShort = row.trend_short ?? 0.0;
  const inWindow = row.earnings_before_expiry != null;
  let safety =
    row.delta != null
      ? clamp(1.0 + row.delta, 0.0, 1.0)
      : maxDropSafety(row.strike, row.strike_from, row.strike_to);
  if (inWindow) safety *= p.earningsSafetyMultiplier;
  return scoreParts(sharpe, safety, ror, trendShort, p);
}

// Mirrors top_picks_from_rows: score-descending (stable on ties), per-symbol
// dedupe, per-sector dedupe with "Unknown" exempt, take `count`.
// entries: [{ row, score }] — score from rescoreRow, null allowed.
export function topPicks(entries, count = PRODUCTION.topPicksCount) {
  const scored = entries
    .map((e, i) => ({ ...e, i }))
    .filter((e) => e.score != null)
    .sort((a, b) => b.score - a.score || a.i - b.i);
  const seenSymbols = new Set();
  const seenSectors = new Set();
  const picks = [];
  for (const e of scored) {
    if (picks.length >= count) break;
    const { row } = e;
    if (seenSymbols.has(row.underlying)) continue;
    if (row.sector !== "Unknown" && seenSectors.has(row.sector)) continue;
    seenSymbols.add(row.underlying);
    if (row.sector !== "Unknown") seenSectors.add(row.sector);
    picks.push(e);
  }
  return picks;
}

// True when params are exactly the production defaults (drives the
// "production defaults" vs "custom" state in the GUI).
export function isProduction(p) {
  return (
    p.weightSharpe === PRODUCTION.weightSharpe &&
    p.weightSafety === PRODUCTION.weightSafety &&
    p.weightReturn === PRODUCTION.weightReturn &&
    p.minRateOfReturn === PRODUCTION.minRateOfReturn
  );
}
